@startuml
actor actor as 用户

用户 -> 系统: 登录请求
database database as 数据库
系统 -> 数据库 : 根据用户名已经密码查询user表数据库
数据库 -> 系统 : 根据查询条件返回信息
系统 -> 系统 : 根据数据的返回作判断，\n 如果数据存在，则去查询\n数据库获取用户菜单
系统 -> 数据库 : 根据用户id获取用户角色以及用户菜单
数据库 -> 系统 : 根据查询条件返回信息
系统 -> 用户: 登录信息返回
@enduml
